x-versions:
  guacd: &guacd-version "guacamole/guacd:1.6.0"
  guacamole: &guacamole-version "guacamole/guacamole:1.6.0"
  firefox: &firefox-version "jlesage/firefox:latest"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  guacamole-guacd:
    image: *guacd-version
    container_name: guacamole-guacd
    hostname: guacamole-guacd
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      GUACD_LOG_LEVEL: "debug"
    healthcheck:
      test: "nc -z 127.0.0.1 4822 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - guacamole
    logging: *default-logging
    labels:
      wud.watch: 'true'
      wud.display.icon: 'sh-apache-guacamole-dark'
      wud.display.name: 'Guacamole daemon'
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/apache/guacamole-server/releases/tag/v$${major}.$${minor}.$${patch}'

  guacamole-firefox:
    image: *firefox-version
    container_name: guacamole-firefox
    hostname: guacamole-firefox
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    shm_size: 2G
    mem_limit: 2G
    environment:
      USER_ID: "${DOCKER_PUID}"
      GROUP_ID: "${DOCKER_PGID}"
      TZ: "${TZ}"
      KEEP_APP_RUNNING: 1
      DARK_MODE: 1
      WEB_LISTENING_PORT: 5801
      VNC_LISTENING_PORT: 5901
      SECURE_CONNECTION: 0
      SECURE_CONNECTION_VNC_METHOD: "SSL"
      SECURE_CONNECTION_CERTS_CHECK_INTERVAL: 60
      FF_OPEN_URL: "https://fp.${DOMAIN_NAME}"
    ports:
      - "5801:5801"
    volumes:
      - /opt/docker/guacamole/guacamole-firefox_config:/config:rw
    networks:
      - guacamole
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.display.name: "Guacamole - Firefox"
      wud.display.icon: "sh-apache-guacamole-dark"

  guacamole:
    image: *guacamole-version
    container_name: guacamole
    hostname: guacamole
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 1G
    environment:
      POSTGRESQL_DATABASE: "guacamole"
      POSTGRESQL_USER: "guacamole"
      POSTGRESQL_PASSWORD: "${GUACAMOLE_DB_PASS}"
      GUACD_HOSTNAME: "guacamole-guacd"
      GUACD_PORT: "4822"
      POSTGRESQL_HOSTNAME: "10.10.1.13"
      TOTP_ENABLED: "true"
      WEBAPP_CONTEXT: "ROOT"
      CATALINA_OPTS: "-Djava.net.preferIPv4Stack=true"
    depends_on:
      guacamole-guacd:
        condition: service_healthy
    networks:
      - guacamole
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.guacamole.rule: "Host(`avocado.${DOMAIN_NAME}`)"
      traefik.http.routers.guacamole.entrypoints: "websecure"
      traefik.http.routers.guacamole.tls: "true"
      traefik.http.routers.guacamole.tls.certresolver: "letsencrypt"
      traefik.http.routers.guacamole.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.guacamole.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.guacamole.middlewares: "secHeaders@file"
      traefik.http.services.guacamole.loadbalancer.server.port: "8080"
      homepage.group: Home
      homepage.name: Guacamole
      homepage.description: "Remote access"
      homepage.href: https://avocado.${DOMAIN_NAME}
      homepage.icon: "sh-apache-guacamole-light.png"
      homepage.siteMonitor: "https://avocado.${DOMAIN_NAME}"
      wud.watch: 'true'
      wud.display.icon: 'sh-apache-guacamole-dark'
      wud.display.name: 'Guacamole'
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/apache/guacamole-server/releases/tag/v$${major}.$${minor}.$${patch}'

networks:
  guacamole:
    name: guacamole
    driver: bridge
    external: false
  traefik:
    external: true
