x-versions:
  adventurelog-frontend: &adventurelog-frontend-version "ghcr.io/seanmorley15/adventurelog-frontend:v0.12.0"
  adventurelog-backend: &adventurelog-backend-version "ghcr.io/seanmorley15/adventurelog-backend:v0.12.0"
  postgis: &postgis-version "postgis/postgis:17-3.6-alpine"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  adventurelog-postgis:
    image: *postgis-version
    container_name: adventurelog-postgis
    hostname: adventurelog-postgis
    ipc: private
    restart: unless-stopped
    entrypoint: ['docker-entrypoint.sh']
    command: ['postgres']
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m
    environment:
      POSTGRES_USER: "adventurelog"
      PGUSER: "adventurelog"
      POSTGRES_PASSWORD: "${ADVENTURELOG_DB_PASS}"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', 'adventurelog', '-d', 'adventurelog']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - /opt/docker/adventurelog/postgis_data:/var/lib/postgresql/data
    networks:
      - adventurelog
      - adminer
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^17-\d+\.\d+-alpine$$'
      wud.display.name: "AdventureLog - Postgis"
      wud.display.icon: "sh-adventurelog"

  adventurelog-web:
    image: *adventurelog-frontend-version
    container_name: adventurelog-web
    hostname: adventurelog-web
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      PUBLIC_SERVER_URL: "http://server:8000"
      BODY_SIZE_LIMIT: "100000"
    depends_on:
      - adventurelog-server
    networks:
      - adventurelog
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.adventurelog.rule: "Host(`adventure.${DOMAIN_NAME}`)"
      traefik.http.routers.adventurelog.entrypoints: "websecure"
      traefik.http.routers.adventurelog.tls: "true"
      traefik.http.routers.adventurelog.tls.certresolver: "letsencrypt"
      traefik.http.routers.adventurelog.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.adventurelog.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.adventurelog.middlewares: "secHeaders@file"
      traefik.http.services.adventurelog.loadbalancer.server.port: "3000"
      homepage.group: "Home"
      homepage.name: "AdventureLog"
      homepage.icon: "adventurelog.png"
      homepage.href: "https://adventure.${DOMAIN_NAME}"
      homepage.description: "Media tracker"
      homepage.siteMonitor: "https://adventure.${DOMAIN_NAME}"
      wud.watch: "true"
      wud.tag.include: '^v?\d+\.\d+\.\d+$$'
      wud.display.name: "AdventureLog - Frontend"
      wud.display.icon: "sh:adventurelog"
      wud.link.template: "https://github.com/seanmorley15/AdventureLog/releases/tag/v$${major}.$${minor}.$${patch}"

  adventurelog-server:
    image: *adventurelog-backend-version
    container_name: adventurelog-server
    hostname: adventurelog-server
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      PGHOST: "adventurelog-postgis"
      PGDATABASE: "adventurelog"
      PGUSER: "adventurelog"
      PGPASSWORD: "${ADVENTURELOG_DB_PASS}"
      SECRET_KEY: "${ADVENTURELOG_SECRET_KEY}"
      DJANGO_ADMIN_USERNAME: "admin"
      DJANGO_ADMIN_PASSWORD: "${ADVENTURELOG_ADMIN_PASS}"
      DJANGO_ADMIN_EMAIL: "${ADMIN_EMAIL}"
      PUBLIC_URL: "https://adventure.${DOMAIN_NAME}"
      CSRF_TRUSTED_ORIGINS: "https://adventure.${DOMAIN_NAME}"
      DEBUG: "false"
      FRONTEND_URL: "https://adventure.${DOMAIN_NAME}"
    depends_on:
      adventurelog-postgis:
        condition: service_healthy
    volumes:
      - /opt/docker/adventurelog/adventurelog-media:/code/media
    networks:
      - adventurelog
      - traefik
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^v?\d+\.\d+\.\d+$$'
      wud.display.name: "AdventureLog - Backend"
      wud.display.icon: "sh:adventurelog"
      wud.link.template: "https://github.com/seanmorley15/AdventureLog/releases/tag/v$${major}.$${minor}.$${patch}"

networks:
  adventurelog:
    external: false
    name: adventurelog
    driver: bridge
  adminer:
    external: true
  traefik:
    external: true
