x-versions:
  openttd: &openttd-version "bateau/openttd:latest"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

name: openttd
services:
  openttd:
    image: *openttd-version
    container_name: openttd
    hostname: openttd
    ipc: private
    restart: unless-stopped
    entrypoint:
      - /usr/bin/dumb-init
      - --rewrite
      - "15:3"
      - --rewrite
      - "9:3"
      - --
    command:
      - /openttd.sh
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      DEBUG: "1"
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: "100"
      PUID: "1002"
      loadgame: last-autosave
    ports:
      - 3978:3978/tcp
      - 3978:3978/udp
      - 3979:3979/tcp
      - 3979:3979/udp
    volumes:
      - /opt/docker/openttd/openttd_config:/home/openttd/.config/openttd
      - /opt/docker/openttd/openttd_save:/home/openttd/.openttd/save
      - /opt/docker/openttd/openttd_data:/home/openttd/.local/share/openttd
    networks:
      - openttd
    logging: *default-logging
    labels:
      wud.watch: "false"

networks:
  openttd:
    name: openttd
    driver: bridge
