x-versions:
  freshrss: &freshrss-version "freshrss/freshrss:1.28.1"
  rss-bridge: &rss-bridge-version "rssbridge/rss-bridge:latest"
  postgres: &postgres-version "docker.io/postgres:18.3-alpine"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  freshrss-rssbridge:
    image: *rss-bridge-version
    ipc: private
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 256M
    entrypoint: ["sh", "-c", "/app/bin/cache-clear && exec /app/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/80 && echo HTTP OK || echo HTTP FAIL'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "4746:80"
    volumes:
      - /opt/docker/freshrss/freshrss-rssbridge_config:/config
    networks:
      - freshrss
    logging: *default-logging

  freshrss-postgres:
    image: *postgres-version
    ipc: private
    restart: unless-stopped
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 50m
    environment:
      POSTGRES_DB: "freshrss"
      POSTGRES_PASSWORD: "${FRESHRSS_POSTGRES_PASS}"
      POSTGRES_USER: "freshrss"
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    volumes:
      - /opt/docker/freshrss/freshrss_postgres-data:/var/lib/postgresql/18/docker
    networks:
      - freshrss
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^17\.\d+-alpine$$'
      wud.link.template: 'https://github.com/postgres/postgres/releases/tag/REL_$${major}_$${minor}'
      wud.display.name: "FreshRSS - Postgres"
      wud.display.icon: "sh-freshrss"

  freshrss:
    image: *freshrss-version
    container_name: freshrss
    ipc: private
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      TRUSTED_PROXIES: "traefik"
      TZ: "${TZ}"
      BASE_URL: "https://rss.${DOMAIN_NAME}"
      CRON_MIN: "*/10"
      ADMIN_EMAIL: "ddd@ddd.pl"
      ADMIN_PASSWORD: "freshrss"
      ADMIN_API_PASSWORD: "freshrss"
      DB_TYPE: "pgsql"
      DB_HOST: ""
      DB_USER: "freshrss"
      DB_BASE: "freshrss"
      DB_PASS: "${FRESHRSS_POSTGRES_PASS}"
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url https://rss.${DOMAIN_NAME}
        --db-base freshrss
        --db-host freshrss-postgres
        --db-password ${FRESHRSS_POSTGRES_PASS}
        --db-type pgsql
        --db-user freshrss
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${FRESHRSS_ADMIN_API_PASS}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${FRESHRSS_ADMIN_PASS}
        --user admin
    depends_on:
      freshrss-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3
    ports:
      - "8020:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/freshrss/freshrss_data:/var/www/FreshRSS/data
      - /opt/docker/freshrss/freshrss_extensions:/var/www/FreshRSS/extensions
    networks:
      - freshrss
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.freshrss.rule: "Host(`rss.${DOMAIN_NAME}`)"
      traefik.http.routers.freshrss.entrypoints: "websecure"
      traefik.http.routers.freshrss.tls: "true"
      traefik.http.routers.freshrss.tls.certresolver: "letsencrypt"
      traefik.http.routers.freshrss.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.freshrss.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.freshrss.middlewares: "secHeaders@file"
      traefik.http.services.freshrss.loadbalancer.server.port: "80"
      homepage.group: "Home"
      homepage.name: "FreshRSS"
      homepage.icon: "sh-freshrss.png"
      homepage.href: "https://rss.${DOMAIN_NAME}"
      homepage.description: "RSS news reader and aggregator"
      homepage.siteMonitor: "https://rss.${DOMAIN_NAME}"
      homepage.widget.type: "freshrss"
      homepage.widget.url: "http://10.10.1.13:8020"
      homepage.widget.username: "${HOMEPAGE_FRESHRSS_MICHAL_USERNAME}"
      homepage.widget.password: "${HOMEPAGE_FRESHRSS_MICHAL_PASSWORD}"
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.display.name: "FreshRSS"
      wud.display.icon: "sh:freshrss"
      wud.link.template: "https://github.com/FreshRSS/FreshRSS/releases/$${major}.$${minor}.$${patch}"

networks:
  freshrss:
    name: freshrss
    driver: bridge
  traefik:
    name: traefik
    external: true
