x-versions:
  fireflyiii: &fireflyiii-version "fireflyiii/core:version-6.5.9"
  fireflyiii-dataimporter: &fireflyiii-dataimporter-version "fireflyiii/data-importer:version-2.2.3"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  fireflyiii:
    image: *fireflyiii-version
    container_name: fireflyiii
    hostname: fireflyiii
    ipc: private
    restart: unless-stopped
    user: www-data
    working_dir: /var/www/html
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 1G
    environment:
      DB_CONNECTION: "pgsql"
      DB_PORT: "5432"
      DB_HOST: "10.10.1.13"
      DB_DATABASE: "fireflyiii"
      DB_USERNAME: "fireflyiii"
      DB_PASSWORD: "${FIREFLYIII_DB_PASS}"
      APP_KEY: "${FIREFLYIII_APP_KEY}"
      DEFAULT_LANGUAGE: "en_GB"
      TZ: "${TZ}"
      ENABLE_EXTERNAL_RATES: "true"
      APP_URL: "https://finance.${DOMAIN_NAME}"
      TRUSTED_PROXIES: "*"
      FIREFLY_III_LAYOUT: "v2"
      SESSION_DRIVER: "file"
    ports:
      - 4747:8080/tcp
    volumes:
      - /opt/docker/fireflyiii/fireflyiii_upload:/var/www/html/storage/upload
    networks:
      - fireflyiii
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.fireflyiii.entrypoints: websecure
      traefik.http.routers.fireflyiii.rule: Host(`finance.${DOMAIN_NAME}`)
      traefik.http.routers.fireflyiii.tls: "true"
      traefik.http.routers.fireflyiii.tls.certresolver: letsencrypt
      traefik.http.routers.fireflyiii.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.fireflyiii.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.fireflyiii.middlewares: "secHeaders@file"
      traefik.http.services.fireflyiii.loadbalancer.server.port: "8080"
      wud.watch: "true"
      wud.tag.include: '^version-\d+\.\d+\.\d+$$'
      wud.display.name: "Firefly III"
      wud.display.icon: "sh:firefly-iii"
      wud.link.template: "https://github.com/firefly-iii/firefly-iii/releases/v$${major}.$${minor}.$${patch}"
      homepage.group: "Finance"
      homepage.name: "Firefly III"
      homepage.icon: "firefly.png"
      homepage.href: "https://finance.${DOMAIN_NAME}"
      homepage.siteMonitor: "https://finance.${DOMAIN_NAME}"
      homepage.description: "Personal finance manager"
      homepage.widget.type: "firefly"
      homepage.widget.url: "http://10.10.1.13:4747"
      homepage.widget.key: "${HOMEPAGE_MICHAL_FIREFLY_API}"

  fireflyiii_paulina_dataimporter:
    image: *fireflyiii-dataimporter-version
    container_name: fireflyiii_paulina_dataimporter
    hostname: fireflyiii_paulina_dataimporter
    ipc: private
    restart: unless-stopped
    user: www-data
    working_dir: /var/www/html
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      FIREFLY_III_ACCESS_TOKEN: "${FIREFLYIII_PAULINA_ACCESS_TOKEN}"
      FIREFLY_III_URL: "http://fireflyiii:8080"
      NORDIGEN_ID: "${FIREFLYIII_PAULINA_NORD_ID}"
      NORDIGEN_KEY: "${FIREFLYIII_PAULINA_NORD_KEY}"
      CAN_POST_AUTOIMPORT: "true"
      IMPORT_DIR_ALLOWLIST: "/import"
      AUTO_IMPORT_SECRET: "${FIREFLYIII_PAULINA_AUTOIMPORT_KEY}"
    ports:
      - 4749:8080/tcp
    volumes:
      - /opt/docker/fireflyiii/fireflyiii_dataimporter_paulina_upload:/var/www/html/storage/upload
      - /Data/IT/filebrowser-data/users/paulina/Paulina-Documents/firefly_configurations:/import:ro
    networks:
      - fireflyiii
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^version-\d+\.\d+\.\d+$$'
      wud.display.name: "Firefly III Data importer"
      wud.display.icon: "sh:firefly-iii"
      wud.link.template: "https://github.com/firefly-iii/data-importer/releases/v$${major}.$${minor}.$${patch}"

  fireflyiii_michal_dataimporter:
    image: *fireflyiii-dataimporter-version
    container_name: fireflyiii_michal_dataimporter
    hostname: fireflyiii_michal_dataimporter
    ipc: private
    restart: unless-stopped
    user: www-data
    working_dir: /var/www/html
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      FIREFLY_III_ACCESS_TOKEN: "${FIREFLYIII_MICHAL_ACCESS_TOKEN}"
      FIREFLY_III_URL: "http://fireflyiii:8080"
      NORDIGEN_ID: "${FIREFLYIII_MICHAL_NORD_ID}"
      NORDIGEN_KEY: "${FIREFLYIII_MICHAL_NORD_KEY}"
      CAN_POST_AUTOIMPORT: "true"
      IMPORT_DIR_ALLOWLIST: "/import"
      AUTO_IMPORT_SECRET: "${FIREFLYIII_MICHAL_AUTOIMPORT_KEY}"
    ports:
      - 4748:8080/tcp
    volumes:
      - /Data/IT/filebrowser-data/users/michal/Michal-Documents/firefly_configurations:/import:ro
      - /opt/docker/fireflyiii/fireflyiii_dataimporter_michal_upload:/var/www/html/storage/upload
    networks:
      - fireflyiii
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^version-\d+\.\d+\.\d+$$'
      wud.display.name: "Firefly III Data importer"
      wud.display.icon: "sh:firefly-iii"
      wud.link.template: "https://github.com/firefly-iii/data-importer/releases/v$${major}.$${minor}.$${patch}"

networks:
  fireflyiii:
    name: fireflyiii
    driver: bridge
    external: false
  traefik:
    external: true
