x-versions:
  cronicle: &cronicle-version "peterbuga/cronicle-docker:0.9.130"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

name: cronicle

services:
  cronicle:
    image: *cronicle-version
    container_name: cronicle
    hostname: cronicle
    ipc: private
    restart: unless-stopped
    working_dir: /opt/cronicle
#    entrypoint:
#      - docker-entrypoint.sh
#    command: ['node','bin/docker-entrypoint.js']
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      CRONICLE_color: "1"
      CRONICLE_echo: "1"
      CRONICLE_foreground: "1"
      CRONICLE_base_app_url: "http://10.10.1.13:3012"
      CRONICLE_secret_key: "${CRONICLE_SECRET_KEY}"
    ports:
      - 3012:3012/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /opt/docker/cronicle/cronicle_data:/opt/cronicle/data
      - /opt/docker/cronicle/cronicle_logs:/opt/cronicle/logs
      - /opt/docker/cronicle/cronicle_plugins:/opt/cronicle/plugins
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cronicle
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^v?\d+\.\d+\.\d+$$'
      wud.link.template: "https://github.com/jhuckaby/Cronicle/releases/tag/v$${major}.$${minor}.$${patch}"
      wud.display.name: "Cronicle"
      wud.display.icon: "sh:cronicle"

networks:
  cronicle:
    name: cronicle
    driver: bridge
