name: cronicle
services:
  cronicle:
    cap_drop:
      - ALL
    command: ['node','bin/docker-entrypoint.js']
    container_name: cronicle
    entrypoint:
      - docker-entrypoint.sh
    environment:
      CRONICLE_color: "1"
      CRONICLE_echo: "1"
      CRONICLE_foreground: "1"
    hostname: cronicle
    image: soulteary/cronicle:latest
    ipc: private
    logging:
      driver: json-file
    networks:
      cronicle: null
    ports:
      - mode: ingress
        target: 3012
        published: "3012"
        protocol: tcp
    restart: unless-stopped
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        bind:
          create_host_path: true
      - type: bind
        source: /opt/docker/cronicle/cronicle_data
        target: /opt/cronicle/data
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
    working_dir: /opt/cronicle
networks:
  cronicle:
    name: cronicle
    driver: bridge