x-versions:
  homepage: &homepage-version "ghcr.io/gethomepage/homepage:v1.12.1"
  socket-proxy: &socket-proxy-version "wollomatic/socket-proxy:1.11.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  homepage-socket-proxy:
    image: *socket-proxy-version
    ipc: private
    command:
      - '-loglevel=debug'
      - '-allowfrom=homepage'
      - '-listenip=0.0.0.0'
      - '-allowGET=/(version|containers/.*)'
      - '-watchdoginterval=1200'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "65534:${DOCKER_SOCKET_GID}"
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: "https://github.com/wollomatic/socket-proxy/releases/tag/$${major}.$${minor}.$${patch}"
      wud.display.name: 'Docker Socket Proxy - Homepage'
      wud.display.icon: 'mdi:connection'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homepage

  homepage:
    image: *homepage-version
    container_name: homepage
    ipc: private
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    mem_limit: 512M
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "fp.${DOMAIN_NAME},10.10.1.13:3008"
      PUID: "${DOCKER_PUID}"
      PGID: "${DOCKER_PGID}"
    ports:
      - 3008:3000
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`fp.${DOMAIN_NAME}`)"
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.tls.certresolver: "letsencrypt"
      traefik.http.routers.homepage.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.homepage.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.homepage.middlewares: "secHeaders@file,authelia-auth@docker"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
      wud.watch: "true"
      wud.tag.include: '^v?\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/gethomepage/homepage/releases/tag/v$${major}.$${minor}.$${patch}'
      wud.display.name: 'Homepage'
      wud.display.icon: 'sh:homepage'
    volumes:
      - /opt/docker/homepage/homepage_config:/app/config
    depends_on:
      - homepage-socket-proxy
    networks:
      - homepage
      - traefik

networks:
  homepage:
    name: homepage
    driver: bridge
    external: false
  traefik:
    external: true
