x-versions:
  ttrss: &ttrss-version "wangqiru/ttrss:latest"
  mercury-parser: &mercury-parser-version "wangqiru/mercury-parser-api:latest"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mercury-parser-api:
    image: *mercury-parser-version
    container_name: mercury-parser-api
    hostname: mercury-parser-api
    ipc: private
    restart: unless-stopped
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 256M
    ports:
      - 3000:3000/tcp
    networks:
      - ttrss
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.display.name: "TT-RSS - Mercury Parser"
      wud.display.icon: "sh:tiny-tiny-rss"

  ttrss:
    image: *ttrss-version
    container_name: ttrss
    hostname: ttrss
    ipc: private
    restart: unless-stopped
    entrypoint: ['sh','/docker-entrypoint.sh']
    working_dir: /var/www
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      DB_HOST: "10.10.1.13"
      SELF_URL_PATH: "https://ttrss.${DOMAIN_NAME}"
      DB_USER: "ttrss"
      DB_PASS: "${TTRSS_DB_PASS}"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ALLOW_PORTS: "80,443"
      DB_NAME: "ttrss"
      LD_PRELOAD: "/usr/lib/preloadable_libiconv.so php"
      DB_PORT: "5432"
      ENABLE_PLUGINS: "auth_internal,fever"
      SESSION_COOKIE_LIFETIME: "24"
      SINGLE_USER_MODE: "false"
      LOG_DESTINATION: "sql"
      FEED_LOG_QUIET: "false"
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - 2015:80/tcp
    volumes:
      - /opt/docker/ttrss/ttrss_fever:/var/www/plugins/fever
    networks:
      - ttrss
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.ttrss.entrypoints: websecure
      traefik.http.routers.ttrss.rule: Host(`ttrss.${DOMAIN_NAME}`)
      traefik.http.routers.ttrss.tls: "true"
      traefik.http.routers.ttrss.tls.certresolver: letsencrypt
      traefik.http.routers.ttrss.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.ttrss.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.ttrss.middlewares: "secHeaders@file"
      traefik.http.services.ttrss.loadbalancer.server.port: "80"
      wud.watch: "true"
      wud.display.name: "TT-RSS"
      wud.display.icon: "sh:tiny-tiny-rss"

networks:
  ttrss:
    name: ttrss
    driver: bridge
    external: false
  traefik:
    external: true
