x-versions:
  navidrome: &navidrome-version "deluan/navidrome:0.61.1"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  navidrome:
    image: *navidrome-version
    container_name: navidrome
    hostname: navidrome
    ipc: private
    restart: unless-stopped
    user: "${MEDIA_PUID}:${MEDIA_PGID}"
    entrypoint: ['/app/navidrome']
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    ports:
      - 4533:4533/tcp
    volumes:
      - /opt/docker/navidrome/navidrome_data:/data
      - /Data/Music:/music:ro
    networks:
      - navidrome
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.routers.navidrome.rule: Host(`music.${DOMAIN_NAME}`)
      traefik.http.routers.navidrome.tls: "true"
      traefik.http.routers.navidrome.tls.certresolver: letsencrypt
      traefik.http.routers.navidrome.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.navidrome.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.routers.navidrome.middlewares: "secHeaders@file"
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"
      homepage.group: "Home"
      homepage.name: "Navidrome"
      homepage.icon: "sh-navidrome.png"
      homepage.href: "https://music.${DOMAIN_NAME}"
      homepage.description: "Music streamer"
      homepage.siteMonitor: "https://music.${DOMAIN_NAME}"
      homepage.widget.type: "navidrome"
      homepage.widget.url: "http://10.10.1.13:4533"
      homepage.widget.user: "${HOMEPAGE_NAVIDROME_USER}"
      homepage.widget.token: "${HOMEPAGE_NAVIDROME_TOKEN}"
      homepage.widget.salt: "${HOMEPAGE_NAVIDROME_SALT}"
      wud.watch: "true"
      wud.tag.include: '^v?\d+\.\d+\.\d+$$'
      wud.display.name: "Navidrome"
      wud.display.icon: "sh:navidrome"
      wud.link.template: "https://github.com/navidrome/navidrome/releases/v$${major}.$${minor}.$${patch}"

networks:
  navidrome:
    name: navidrome
    driver: bridge
    external: false
  traefik:
    external: true
