x-versions:
  heimdall: &heimdall-version "linuxserver/heimdall:latest"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  heimdall:
    image: *heimdall-version
    container_name: heimdall
    hostname: heimdall
    ipc: private
    restart: unless-stopped
    entrypoint:
      - /init
    working_dir: /
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 256M
    environment:
      TZ: "${TZ}"
      PUID: "${DOCKER_PUID}"
      PGID: "${DOCKER_PGID}"
    ports:
      - 3838:80/tcp
    volumes:
      - /opt/docker/heimdall/heimdall_config:/config
    networks:
      - heimdall
      - traefik
    logging: *default-logging
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.rule: "Host(`fp.${DOMAIN_NAME}`)"
      traefik.http.routers.heimdall.entrypoints: "websecure"
      traefik.http.routers.heimdall.tls: "true"
      traefik.http.routers.heimdall.tls.certresolver: "letsencrypt"
      traefik.http.services.heimdall.loadbalancer.server.port: "80"

networks:
  heimdall:
    name: heimdall
    driver: bridge
    external: false
  traefik:
    external: true
