x-versions:
  postgresql: &postgresql-version "postgres:18-alpine"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgresql:
    image: *postgresql-version
    container_name: postgresql
    hostname: postgresql
    ipc: private
    restart: unless-stopped
    entrypoint: ['docker-entrypoint.sh']
    command: ['postgres']
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256m
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_ADMIN_PASS}"
      PGDATA: "/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432/tcp
    volumes:
      - /opt/docker/postgresql/postgres_data:/var/lib/postgresql/data
    networks:
      - postgresql
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^18\.\d+-alpine$$'
      wud.display.name: "PostgreSQL"
      wud.display.icon: "sh:postgresql"
      wud.link.template: 'https://github.com/postgres/postgres/releases/tag/REL_$${major}_$${minor}'

networks:
  postgresql:
    name: postgresql
    driver: bridge
    external: false
