x-versions:
  mariadb: &mariadb-version "linuxserver/mariadb:11.4.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mariadb:
    image: *mariadb-version
    container_name: mariadb
    hostname: mariadb
    ipc: private
    restart: unless-stopped
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          memory: 512m
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ADMIN_PASS}"
      MYSQL_DIR: "/config"
      DATADIR: "/config/databases"
      PUID: "${DOCKER_PUID}"
      PGID: "${DOCKER_PGID}"
      TZ: "${TZ}"
    ports:
      - 3306:3306/tcp
    volumes:
      - /opt/docker/mariadb/mariadb_data:/config
    networks:
      - mariadb
    logging: *default-logging
    labels:
      wud.display.name: "MariaDB"
      wud.display.icon: "sh-mariadb"
      wud.watch: "true"
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/MariaDB/server/releases/tag/mariadb-$${major}.$${minor}.$${patch}'

networks:
  mariadb:
    name: mariadb
    driver: bridge
    external: false
