x-versions:
  cloudflared: &cloudflared-version "cloudflare/cloudflared:2026.3.0"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  cloudflared:
    image: *cloudflared-version
    container_name: cloudflared-tunnel
    ipc: private
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARED_TOKEN}"
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:20241", "ready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
      start_interval: 3s
    networks:
      - cloudflared
    logging: *default-logging

networks:
  cloudflared:
    name: cloudflared
    driver: bridge
    external: false
