x-versions:
  socket-proxy: &socket-proxy-version "wollomatic/socket-proxy:1.11.4"
  repliqate: &repliqate-version "lminlone/repliqate:v0.2.1"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  repliqate-socket-proxy:
    image: *socket-proxy-version
    ipc: private
    command:
      - '-loglevel=info'
      - '-allowfrom=repliqate'
      - '-listenip=0.0.0.0'
      - '-allowGET=/(containers/.*|images/.*|events|info|version|_ping|volumes/.*)'
      - '-allowPOST=/(containers/.*|images/.*)'
      - '-allowDELETE=/(containers/.*|images/.*)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=1200'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "65534:${DOCKER_SOCKET_GID}"
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - repliqate
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: "https://github.com/wollomatic/socket-proxy/releases/tag/$${major}.$${minor}.$${patch}"
      wud.display.name: 'Docker Socket Proxy - Repliqate'
      wud.display.icon: 'mdi:connection'

  repliqate:
    image: *repliqate-version
    container_name: repliqate
    ipc: private
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 512M
    environment:
      DOCKER_SOCK_PATH: "tcp://repliqate-socket-proxy:2375"
    volumes:
      - /Data/IT/Docker_backups:/var/repliqate
      - /opt/docker:/var/lib/docker/volumes:ro
    networks:
      - repliqate
    depends_on:
      - repliqate-socket-proxy
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.watch.digest: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: "https://github.com/lminlone/repliqate/releases/tag/v$${major}$${minor}$${patch}"
      wud.display.name: "Repliqate"
      wud.display.icon: "sh:repliqate"

networks:
  repliqate:
    name: repliqate
    driver: bridge
    external: false
