services:
  repliqate:
    image: lminlone/repliqate
    container_name: repliqate
    volumes:
      - /path/to/backups:/var/repliqate
      - /opt/docker:/var/lib/docker/volumes:ro

networks:
  repliqate:
    external: false
    driver: bridge
    name: repliqate