x-versions:
  esphome: &esphome-version "ghcr.io/esphome/esphome:2025.5.2"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  esphome:
    image: *esphome-version
    container_name: esphome
    ipc: private
    restart: unless-stopped
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 2G
    environment:
      TZ: "${TZ}"
    healthcheck:
      test: >
        curl -sf --max-time 2 http://localhost:6052/ | grep "ESPHome Dashboard" || exit 1
    ports:
      - 6052:6052
    volumes:
      - /opt/docker/esphome/esphome_config:/config:rw
      - /opt/docker/esphome/esphome_pio:/.platformio:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - esphome
    logging: *default-logging
    labels:
      wud.watch: "false"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/esphome/esphome/releases/tag/v$${major}.$${minor}.$${patch}'
      wud.display.name: 'ESPHome'
      wud.display.icon: 'sh:esphome'
      homepage.group: "Smart Home"
      homepage.name: "ESPHome"
      homepage.icon: "esphome.png"
      homepage.href: "http://10.10.1.13:6052"
      homepage.siteMonitor: "http://10.10.1.13:6052"
      homepage.description: "ESP device manager"
      homepage.widget.type: "esphome"
      homepage.widget.url: "http://10.10.1.13:6052"

networks:
  esphome:
    name: esphome
    driver: bridge
    external: false
