x-versions:
  harborguard: &harborguard-version "ghcr.io/harborguard/harborguard:latest"
  postgres: &postgres-version "postgres:18.3-alpine"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  harborguard:
    image: *harborguard-version
    ipc: private
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 512M
    environment:
      MAX_CONCURRENT_SCANS: "5"
      PORT: "3005"
      DATABASE_URL: "postgresql://harborguard:${HARBORGUARD_DB_PASS}@harborguard-postgres:5432/harborguard"
      HEALTH_CHECK_ENABLED: "true"
    depends_on:
      harborguard-postgres:
        condition: service_healthy
    ports:
      - "3005:3005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - harborguard
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      wud.display.name: "HarbourGuard"
      wud.display.icon: "sh-harbourguard"
      wud.digest: "true"
      wud.watch: "true"

  harborguard-postgres:
    image: *postgres-version
    container_name: harborguard-postgres
    ipc: private
    restart: unless-stopped
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 50m
    environment:
      POSTGRES_DB: "harborguard"
      POSTGRES_USER: "harborguard"
      POSTGRES_PASSWORD: "${HARBORGUARD_DB_PASS}"
      PGDATA: "/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    volumes:
      - /opt/docker/harborguard/postgres_data:/var/lib/postgresql/data
    networks:
      - harborguard
      - adminer
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^18\.\d+-alpine$$'
      wud.link.template: 'https://github.com/postgres/postgres/releases/tag/REL_$${major}_$${minor}'
      wud.display.name: "Harborguard - Postgres"
      wud.display.icon: "sh-harborguard"

networks:
  harborguard:
    name: harborguard
    driver: bridge
    external: false
  adminer:
    external: true
