services:
  wyd-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-socket-proxy
    restart: unless-stopped
    networks:
      - wyd
    environment:
      CONTAINERS: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    depends_on:
    - wyd-socket-proxy
    environment:
      TZ: "${TZ}"
    ports:
      - 3000:3000
    networks:
      - wyd
networks:
  wyd:
    name: wyd
    driver: bridge
    external: false